all:
  children:
    master:
      hosts:
        124-100.example.com:
    elastic:
      hosts:
        124-101.example.com:
          ip: 192.168.124.101
          k8s_name: 124-101
        124-102.example.com:
          ip: 192.168.124.102
          k8s_name: 124-102
        124-103.example.com:
          ip: 192.168.124.103
          k8s_name: 124-103
      vars:
        vg_data: cl
        lv_data: es1-data
        size_data: 512
        mount_data: /pv/elastic1-data
        vg_master: cl
        lv_master: es1-master
        size_master: 512
        mount_master: /pv/elastic1-master
  vars:
    namespace: elastic1
    cluster_name: elastic1
    cluster_elasticsearch_port: 30200
    network_policies: false
    kubectl_binary: 'kubectl'
    images:
      origin_logging_elasticsearch: 'docker.io/openshift/origin-logging-elasticsearch:latest'
    clientReplicas: 2
    masterReplicas: 3
    dataReplicas: 2
    #clientRunAsUser: 1234
    #masterRunAsUser: 2345
    #dataRunAsUser:   3456
