---
- import_playbook: config.yml

- name: Create persistent volumes
  hosts: oo_first_master
  roles:
  - role: openshift_persistent_volumes
    when: openshift_hosted_registry_storage_glusterfs_swap | default(False)

- name: Create Hosted Resources
  hosts: oo_first_master
  roles:
  - role: openshift_hosted
