---
openshift_cluster_monitoring_operator_image: quay.io/coreos/cluster-monitoring-operator:v0.0.6
openshift_cluster_monitoring_operator_prometheus_operator_repo: quay.io/coreos/prometheus-operator
openshift_cluster_monitoring_operator_prometheus_repo: quay.io/prometheus/prometheus
openshift_cluster_monitoring_operator_alertmanager_repo: quay.io/prometheus/alertmanager
openshift_cluster_monitoring_operator_prometheus_reloader_repo: quay.io/coreos/prometheus-config-reloader
openshift_cluster_monitoring_operator_configmap_reloader_repo: quay.io/coreos/configmap-reload
openshift_cluster_monitoring_operator_prometheus_storage_capacity: "50Gi"
openshift_cluster_monitoring_operator_alertmanager_storage_capacity: "2Gi"

openshift_cluster_monitoring_operator_cluster_id: "{{ openshift_clusterid | default(openshift_master_cluster_public_hostname, true) | default(openshift_master_cluster_hostname, true) | default('openshift', true) }}"

openshift_cluster_monitoring_operator_alertmanager_config: |+
  global:
    resolve_timeout: 5m
  route:
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: default
    routes:
    - match:
        alertname: DeadMansSwitch
      repeat_interval: 5m
      receiver: deadmansswitch
  receivers:
  - name: default
  - name: deadmansswitch
