---
- name: Logging Install Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Logging install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_logging:
          title: "Logging Install"
          playbook: "playbooks/openshift-logging/config.yml"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: Update vm.max_map_count for ES 5.x
  hosts: all
  gather_facts: false
  tasks:
  - name: Checking vm max_map_count value
    command:
      cat /proc/sys/vm/max_map_count
    register: _vm_max_map_count

  - stat:
      path: /etc/sysctl.d/99-elasticsearch.conf
    register: _99_es_conf

  - name: Check for current value of vm.max_map_count in 99-elasticsearch.conf
    command: >
      sed /etc/sysctl.d/99-elasticsearch.conf -e 's/vm.max_map_count=\(.*\)/\1/'
    register: _curr_vm_max_map_count
    when: _99_es_conf.stat.exists

  - name: Updating vm.max_map_count value
    sysctl:
      name: vm.max_map_count
      value: 262144
      sysctl_file: "/etc/sysctl.d/99-elasticsearch.conf"
      reload: yes
    when:
    - _vm_max_map_count.stdout | default(0) | int < 262144 | int or _curr_vm_max_map_count.stdout | default(0) | int < 262144

- name: OpenShift Aggregated Logging
  hosts: oo_first_master
  roles:
  - openshift_logging

- name: Logging Install Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Logging install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_logging:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
