apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: {{ namespace }}
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    component: elasticsearch
    role: data
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: transport
    port: 9300
