apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  namespace: {{ namespace }}
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: docker.io/openshift/origin-logging-elasticsearch:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "KUBERNETES_TRUST_CERT"
          value: "true"
        - name: "SERVICE_DNS"
          value: "elasticsearch"
        - name: "CLUSTER_NAME"
          value: "{{ namespace }}"
        - name: IS_MASTER
          value: "false"
        - name: HAS_DATA
          value: "true"
        - name: "INSTANCE_RAM"
          value: "256m"
        - name: "NODE_QUORUM"
          value: "2"
        - name: "DC_NAME"
          value: "{{ namespace }}"
        - name: "POD_LABEL" # For discovery
          value: "component=elasticsearch"
        - name: "RECOVER_EXPECTED_NODES"
          value: "2"
        - name: "RECOVER_AFTER_TIME"
          value: "5m"
        - name: "READINESS_PROBE_TIMEOUT"
          value: "30"
        - name: "JAVA_OPTS"
          value: "-Dlog4j.debug"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-config
          mountPath: /usr/share/java/elasticsearch/config
        - name: storage
          mountPath: /elasticsearch/persistent
{% if searchguard %}
        - name: searchguard
          mountPath: /etc/elasticsearch/secret
          readOnly: true
{% endif %}
      serviceAccount: elasticsearch                      
      serviceAccountName: elasticsearch
      volumes:
          - name: elasticsearch-config
            configMap:
              name: logging-elasticsearch
{% if searchguard %}
          - name: searchguard
            secret:
              secretName: searchguard
{% endif %}
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: local-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
