apiVersion: v1
kind: List
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: deny-all-namespaces
    namespace: {{ namespace }}
  spec:
    podSelector: {}
    ingress:
    - from:
      - podSelector: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-client-service
    namespace: {{ namespace }}
  spec:
    podSelector:
      matchLabels:
          role: client
    ingress:
    - from:
      ports:
      - protocol: TCP
        port: 9200
