---
# tasks file for elastic

- name: "Ensure tmp directory does not exist on master"
  file:
    state: absent
    path: "/tmp/k8s-local-pv"

- name: "Ensure tmp directory exists on master"
  file:
    path: "/tmp/k8s-local-pv"
    owner: "root"
    group: "root"
    mode: "0700"
    state: directory

- include: ssl-pre.yml
  static: true
  tags:
    - ssl

- name: Create elastic configuration template
  template: src={{ item }} dest=/tmp/k8s-local-pv/{{ item | basename  }}
  with_fileglob:
    - ../templates/elasticsearch.yml
    - ../templates/logging.yml

- name: Create elastic templates
  template: src={{ item }} dest=/tmp/k8s-local-pv/{{ item | basename  }}
  with_fileglob:
    - ../templates/*.yaml

- name:  Create namespace
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/namespace.yaml"

- include: ssl.yml
  static: true
  tags:
    - ssl

- name:  Check if configmap already exists
  shell: "{{ kubectl_binary }} get configmap logging-elasticsearch -n {{ namespace }}"
  register: get_cm_output
  failed_when: false
  changed_when: false

- name: Fail is something seems wrong
  fail:
    msg : "Ooops someting is wrong with kubectl"
  when: '"not found" not in get_cm_output.stderr and get_cm_output.rc != 0'

- name:  Delete configmap
  shell: "{{ kubectl_binary }} delete configmap logging-elasticsearch -n {{ namespace }}"
  when:
    - get_cm_output.rc == 0

- name: Create ElasticSearch configmap
  shell: "{{ kubectl_binary }} create configmap logging-elasticsearch --from-file=/tmp/k8s-local-pv/elasticsearch.yml --from-file=/tmp/k8s-local-pv/logging.yml -n {{ namespace }}"

- name:  Create service account aggregated-logging-elasticsearch
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/elasticsearch.sa.yaml -n {{ namespace }}"

- name:  Create client service
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/es-svc.yaml -n {{ namespace }}"

- name:  Create data service
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/es-data-svc.yaml -n {{ namespace }}"

- name:  Create master service
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/es-master-svc.yaml -n {{ namespace }}"

- name:  Create master deployment
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/es-master-stateful.yaml -n {{ namespace }}"

- name:  Create data deployment (a.k.a. statefulset)
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/es-data-stateful.yaml -n {{ namespace }}"

- name:  Create client deployment
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/es-client.yaml -n {{ namespace }}"

- name:  Check if PodDisruptionBudget already exists
  shell: "{{ kubectl_binary }} get pdb es-master-pdb -n {{ namespace }}"
  register: get_pdb_output
  failed_when: false
  changed_when: false

- name: Fail if something seems wrong
  fail:
    msg : "Ooops someting is wrong with kubectl"
  when: '"not found" not in get_pdb_output.stderr and get_pdb_output.rc != 0'

- name:  Delete PodDisruptionBudget
  shell: "{{ kubectl_binary }} delete pdb/es-master-pdb pdb/es-client-pdb -n {{ namespace }}"
  when:
    - get_pdb_output.rc == 0

- name: Create PodDisruptionBudget
  shell: "{{ kubectl_binary }} create -f /tmp/k8s-local-pv/elasticsearch.pdb.yaml -n {{ namespace }}"

- name: Set up Network Policies
  shell: "{{ kubectl_binary }} apply -f /tmp/k8s-local-pv/networkpolicies.yaml"
  when: network_policies | bool | default(false)
